/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.analytics.message.storage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.sql.Blob;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AnalyticsMessageEntry service. Represents a row in the &quot;AnalyticsMessageEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.analytics.message.storage.model.impl.AnalyticsMessageEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.analytics.message.storage.model.impl.AnalyticsMessageEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AnalyticsMessageEntry
 * @generated
 */
@ProviderType
public interface AnalyticsMessageEntryModel
	extends BaseModel<AnalyticsMessageEntry>, MVCCModel, ShardedModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a analytics message entry model instance should use the {@link AnalyticsMessageEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this analytics message entry.
	 *
	 * @return the primary key of this analytics message entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this analytics message entry.
	 *
	 * @param primaryKey the primary key of this analytics message entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this analytics message entry.
	 *
	 * @return the mvcc version of this analytics message entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this analytics message entry.
	 *
	 * @param mvccVersion the mvcc version of this analytics message entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the analytics message entry ID of this analytics message entry.
	 *
	 * @return the analytics message entry ID of this analytics message entry
	 */
	public long getAnalyticsMessageEntryId();

	/**
	 * Sets the analytics message entry ID of this analytics message entry.
	 *
	 * @param analyticsMessageEntryId the analytics message entry ID of this analytics message entry
	 */
	public void setAnalyticsMessageEntryId(long analyticsMessageEntryId);

	/**
	 * Returns the company ID of this analytics message entry.
	 *
	 * @return the company ID of this analytics message entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this analytics message entry.
	 *
	 * @param companyId the company ID of this analytics message entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this analytics message entry.
	 *
	 * @return the user ID of this analytics message entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this analytics message entry.
	 *
	 * @param userId the user ID of this analytics message entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this analytics message entry.
	 *
	 * @return the user uuid of this analytics message entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this analytics message entry.
	 *
	 * @param userUuid the user uuid of this analytics message entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this analytics message entry.
	 *
	 * @return the user name of this analytics message entry
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this analytics message entry.
	 *
	 * @param userName the user name of this analytics message entry
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this analytics message entry.
	 *
	 * @return the create date of this analytics message entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this analytics message entry.
	 *
	 * @param createDate the create date of this analytics message entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the message of this analytics message entry.
	 *
	 * @return the message of this analytics message entry
	 */
	public Blob getMessage();

	/**
	 * Sets the message of this analytics message entry.
	 *
	 * @param message the message of this analytics message entry
	 */
	public void setMessage(Blob message);

}