/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.analytics.message.storage.model.impl;

import com.liferay.analytics.message.storage.model.AnalyticsMessageEntry;
import com.liferay.analytics.message.storage.model.AnalyticsMessageEntryModel;
import com.liferay.analytics.message.storage.model.AnalyticsMessageEntrySoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AnalyticsMessageEntry service. Represents a row in the &quot;AnalyticsMessageEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>AnalyticsMessageEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnalyticsMessageEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AnalyticsMessageEntryImpl
 * @generated
 */
@JSON(strict = true)
public class AnalyticsMessageEntryModelImpl
	extends BaseModelImpl<AnalyticsMessageEntry>
	implements AnalyticsMessageEntryModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a analytics message entry model instance should use the <code>AnalyticsMessageEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "AnalyticsMessageEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"analyticsMessageEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"destination", Types.VARCHAR}, {"message", Types.VARCHAR},
		{"retryCount", Types.INTEGER}, {"sentDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("analyticsMessageEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("destination", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("message", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("retryCount", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("sentDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AnalyticsMessageEntry (mvccVersion LONG default 0 not null,analyticsMessageEntryId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,destination VARCHAR(75) null,message VARCHAR(75) null,retryCount INTEGER,sentDate DATE null,status INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table AnalyticsMessageEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY analyticsMessageEntry.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AnalyticsMessageEntry.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long STATUS_COLUMN_BITMASK = 2L;

	public static final long CREATEDATE_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AnalyticsMessageEntry toModel(
		AnalyticsMessageEntrySoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		AnalyticsMessageEntry model = new AnalyticsMessageEntryImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setAnalyticsMessageEntryId(
			soapModel.getAnalyticsMessageEntryId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setDestination(soapModel.getDestination());
		model.setMessage(soapModel.getMessage());
		model.setRetryCount(soapModel.getRetryCount());
		model.setSentDate(soapModel.getSentDate());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AnalyticsMessageEntry> toModels(
		AnalyticsMessageEntrySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<AnalyticsMessageEntry> models =
			new ArrayList<AnalyticsMessageEntry>(soapModels.length);

		for (AnalyticsMessageEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public AnalyticsMessageEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _analyticsMessageEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAnalyticsMessageEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _analyticsMessageEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AnalyticsMessageEntry.class;
	}

	@Override
	public String getModelClassName() {
		return AnalyticsMessageEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AnalyticsMessageEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AnalyticsMessageEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnalyticsMessageEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AnalyticsMessageEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AnalyticsMessageEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AnalyticsMessageEntry, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AnalyticsMessageEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AnalyticsMessageEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AnalyticsMessageEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, AnalyticsMessageEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			AnalyticsMessageEntry.class.getClassLoader(),
			AnalyticsMessageEntry.class, ModelWrapper.class);

		try {
			Constructor<AnalyticsMessageEntry> constructor =
				(Constructor<AnalyticsMessageEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<AnalyticsMessageEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AnalyticsMessageEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AnalyticsMessageEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<AnalyticsMessageEntry, Object>>();
		Map<String, BiConsumer<AnalyticsMessageEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<AnalyticsMessageEntry, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", AnalyticsMessageEntry::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<AnalyticsMessageEntry, Long>)
				AnalyticsMessageEntry::setMvccVersion);
		attributeGetterFunctions.put(
			"analyticsMessageEntryId",
			AnalyticsMessageEntry::getAnalyticsMessageEntryId);
		attributeSetterBiConsumers.put(
			"analyticsMessageEntryId",
			(BiConsumer<AnalyticsMessageEntry, Long>)
				AnalyticsMessageEntry::setAnalyticsMessageEntryId);
		attributeGetterFunctions.put(
			"companyId", AnalyticsMessageEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<AnalyticsMessageEntry, Long>)
				AnalyticsMessageEntry::setCompanyId);
		attributeGetterFunctions.put(
			"userId", AnalyticsMessageEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<AnalyticsMessageEntry, Long>)
				AnalyticsMessageEntry::setUserId);
		attributeGetterFunctions.put(
			"userName", AnalyticsMessageEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<AnalyticsMessageEntry, String>)
				AnalyticsMessageEntry::setUserName);
		attributeGetterFunctions.put(
			"createDate", AnalyticsMessageEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<AnalyticsMessageEntry, Date>)
				AnalyticsMessageEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", AnalyticsMessageEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<AnalyticsMessageEntry, Date>)
				AnalyticsMessageEntry::setModifiedDate);
		attributeGetterFunctions.put(
			"destination", AnalyticsMessageEntry::getDestination);
		attributeSetterBiConsumers.put(
			"destination",
			(BiConsumer<AnalyticsMessageEntry, String>)
				AnalyticsMessageEntry::setDestination);
		attributeGetterFunctions.put(
			"message", AnalyticsMessageEntry::getMessage);
		attributeSetterBiConsumers.put(
			"message",
			(BiConsumer<AnalyticsMessageEntry, String>)
				AnalyticsMessageEntry::setMessage);
		attributeGetterFunctions.put(
			"retryCount", AnalyticsMessageEntry::getRetryCount);
		attributeSetterBiConsumers.put(
			"retryCount",
			(BiConsumer<AnalyticsMessageEntry, Integer>)
				AnalyticsMessageEntry::setRetryCount);
		attributeGetterFunctions.put(
			"sentDate", AnalyticsMessageEntry::getSentDate);
		attributeSetterBiConsumers.put(
			"sentDate",
			(BiConsumer<AnalyticsMessageEntry, Date>)
				AnalyticsMessageEntry::setSentDate);
		attributeGetterFunctions.put(
			"status", AnalyticsMessageEntry::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<AnalyticsMessageEntry, Integer>)
				AnalyticsMessageEntry::setStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getAnalyticsMessageEntryId() {
		return _analyticsMessageEntryId;
	}

	@Override
	public void setAnalyticsMessageEntryId(long analyticsMessageEntryId) {
		_analyticsMessageEntryId = analyticsMessageEntryId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getDestination() {
		if (_destination == null) {
			return "";
		}
		else {
			return _destination;
		}
	}

	@Override
	public void setDestination(String destination) {
		_destination = destination;
	}

	@JSON
	@Override
	public String getMessage() {
		if (_message == null) {
			return "";
		}
		else {
			return _message;
		}
	}

	@Override
	public void setMessage(String message) {
		_message = message;
	}

	@JSON
	@Override
	public int getRetryCount() {
		return _retryCount;
	}

	@Override
	public void setRetryCount(int retryCount) {
		_retryCount = retryCount;
	}

	@JSON
	@Override
	public Date getSentDate() {
		return _sentDate;
	}

	@Override
	public void setSentDate(Date sentDate) {
		_sentDate = sentDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AnalyticsMessageEntry.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AnalyticsMessageEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AnalyticsMessageEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AnalyticsMessageEntryImpl analyticsMessageEntryImpl =
			new AnalyticsMessageEntryImpl();

		analyticsMessageEntryImpl.setMvccVersion(getMvccVersion());
		analyticsMessageEntryImpl.setAnalyticsMessageEntryId(
			getAnalyticsMessageEntryId());
		analyticsMessageEntryImpl.setCompanyId(getCompanyId());
		analyticsMessageEntryImpl.setUserId(getUserId());
		analyticsMessageEntryImpl.setUserName(getUserName());
		analyticsMessageEntryImpl.setCreateDate(getCreateDate());
		analyticsMessageEntryImpl.setModifiedDate(getModifiedDate());
		analyticsMessageEntryImpl.setDestination(getDestination());
		analyticsMessageEntryImpl.setMessage(getMessage());
		analyticsMessageEntryImpl.setRetryCount(getRetryCount());
		analyticsMessageEntryImpl.setSentDate(getSentDate());
		analyticsMessageEntryImpl.setStatus(getStatus());

		analyticsMessageEntryImpl.resetOriginalValues();

		return analyticsMessageEntryImpl;
	}

	@Override
	public int compareTo(AnalyticsMessageEntry analyticsMessageEntry) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), analyticsMessageEntry.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AnalyticsMessageEntry)) {
			return false;
		}

		AnalyticsMessageEntry analyticsMessageEntry =
			(AnalyticsMessageEntry)obj;

		long primaryKey = analyticsMessageEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		AnalyticsMessageEntryModelImpl analyticsMessageEntryModelImpl = this;

		analyticsMessageEntryModelImpl._originalCompanyId =
			analyticsMessageEntryModelImpl._companyId;

		analyticsMessageEntryModelImpl._setOriginalCompanyId = false;

		analyticsMessageEntryModelImpl._setModifiedDate = false;

		analyticsMessageEntryModelImpl._originalStatus =
			analyticsMessageEntryModelImpl._status;

		analyticsMessageEntryModelImpl._setOriginalStatus = false;

		analyticsMessageEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AnalyticsMessageEntry> toCacheModel() {
		AnalyticsMessageEntryCacheModel analyticsMessageEntryCacheModel =
			new AnalyticsMessageEntryCacheModel();

		analyticsMessageEntryCacheModel.mvccVersion = getMvccVersion();

		analyticsMessageEntryCacheModel.analyticsMessageEntryId =
			getAnalyticsMessageEntryId();

		analyticsMessageEntryCacheModel.companyId = getCompanyId();

		analyticsMessageEntryCacheModel.userId = getUserId();

		analyticsMessageEntryCacheModel.userName = getUserName();

		String userName = analyticsMessageEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			analyticsMessageEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			analyticsMessageEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			analyticsMessageEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			analyticsMessageEntryCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			analyticsMessageEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		analyticsMessageEntryCacheModel.destination = getDestination();

		String destination = analyticsMessageEntryCacheModel.destination;

		if ((destination != null) && (destination.length() == 0)) {
			analyticsMessageEntryCacheModel.destination = null;
		}

		analyticsMessageEntryCacheModel.message = getMessage();

		String message = analyticsMessageEntryCacheModel.message;

		if ((message != null) && (message.length() == 0)) {
			analyticsMessageEntryCacheModel.message = null;
		}

		analyticsMessageEntryCacheModel.retryCount = getRetryCount();

		Date sentDate = getSentDate();

		if (sentDate != null) {
			analyticsMessageEntryCacheModel.sentDate = sentDate.getTime();
		}
		else {
			analyticsMessageEntryCacheModel.sentDate = Long.MIN_VALUE;
		}

		analyticsMessageEntryCacheModel.status = getStatus();

		return analyticsMessageEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AnalyticsMessageEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AnalyticsMessageEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnalyticsMessageEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((AnalyticsMessageEntry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AnalyticsMessageEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AnalyticsMessageEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnalyticsMessageEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((AnalyticsMessageEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AnalyticsMessageEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private long _analyticsMessageEntryId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _destination;
	private String _message;
	private int _retryCount;
	private Date _sentDate;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _columnBitmask;
	private AnalyticsMessageEntry _escapedModel;

}